/* eslint-disable */
// ═══════════════════════════════════════════════════════════════
// CONSTANTS — Traductions, plans, données statiques
// ═══════════════════════════════════════════════════════════════

const TRANSLATIONS = {
  fr: {
    // Navbar
    appName: "TableMaître",
    logout: "Déconnexion",
    lightMode: "Passer en mode clair",
    darkMode: "Passer en mode sombre",
    codePromo: "🎟️ Code promo",
    // Dashboard
    myEvents: "Mes événements",
    welcome: "Bienvenue",
    searchPlaceholder: "Rechercher un événement ou un invité...",
    newEvent: "+ Nouvel événement",
    noEvents: "Aucun événement pour le moment",
    createFirst: "Créer mon premier événement",
    tables: "tables",
    guests: "invités",
    unseated: "non placés",
    placement: "Placement",
    guestsFound: "invité(s) trouvé(s)",
    duplicate: "Dupliquer cet événement",
    daysAgo: "passé",
    today: "Aujourd'hui !",
    inDays: "Dans",
    days: "j",
    // Event types
    mariage: "Mariage",
    gala: "Gala / Soirée",
    anniversaire: "Anniversaire",
    conference: "Conférence",
    autre: "Autre",
    // Event Editor
    back: "← Projets",
    autoPlace: "✨ Auto-placer",
    placeCards: "🖨 Chevalets",
    floorPlan: "📄 Plan PDF",
    qrCode: "QR Code",
    tabPlan: "🗺 Plan",
    tabList: "📋 Liste",
    tabGuests: "👥 Invités",
    tabFood: "🍽 Alimentation",
    tabConstraints: "⊘ Contraintes",
    tabRoom: "⬡ Salle",
    addTable: "+ Table",
    addGuest: "+ Invité",
    dietSummary: "📋 Récap alimentaire",
    unseatedList: "⚠ NON PLACÉS",
    seeAvailable: "👁 Voir places libres",
    tablesVisible: "✓ Tables visibles",
    clickToPlace: "👆 Cliquez sur une table pour y placer",
    undo: "↩ Annuler",
    // Guests
    search: "Rechercher un invité…",
    exportCSV: "⬇ Export CSV",
    importCSV: "⬆ Import CSV",
    // Table form
    tableNumber: "NUMÉRO",
    tableCapacity: "CAPACITÉ",
    tableShape: "FORME",
    tableLabel: "ÉTIQUETTE",
    tableColor: "COULEUR",
    createTable: "Créer la table",
    deleteTable: "Supprimer la table",
    round: "Ronde",
    rectangular: "Rectangulaire",
    // Guest form
    guestName: "NOM *",
    guestEmail: "EMAIL",
    guestDiet: "RÉGIME",
    guestAllergies: "ALLERGIES",
    guestTable: "TABLE",
    guestNotes: "NOTES",
    addGuestBtn: "Ajouter l'invité",
    noTable: "-- Non placé --",
    // Login
    loginGoogle: "Se connecter avec Google",
    budgetEstimated: "Budget estimé",
    budgetSpent: "Dépensé",
    budgetRemaining: "Restant",
    budgetPerGuest: "Coût / invité",
    budgetActual: "Dépenses réelles",
    budgetGap: "Écart",
    notPaid: "Non payé",
    budgetItems: "Postes de dépenses",
    budgetLines: "Postes budgétaires",
    fillTemplate: "Remplir avec modèle",
    addBudgetLine: "Ajouter un poste",
    budgetItem: "Poste",
    amountEstimated: "Montant estimé (€)",
    amountActual: "Montant réel (€)",
    labelOptional: "Libellé (optionnel)",
    tasksTotal: "Tâches totales",
    tasksDone: "Terminées",
    tasksRemaining: "Restantes",
    newTask: "Nouvelle tâche",
    templateModel: "Modèle type",
    taskLabel: "Tâche",
    priority: "Priorité",
    details: "Précisions",
    stepLabel: "Étape",
    supplierName: "Nom / Société",
    supplierRole: "Rôle / Prestation",
    videographer: "Vidéaste",
    decorator: "Décorateur",
    roleMarried: "Marié(e)",
    roleWitness: "Témoin",
    newConstraint: "Nouvelle contrainte",
    firstGuest: "Premier invité",
    secondGuest: "Deuxième invité",
    separated: "Séparés",
    eventSettings: "Paramètres de l'événement",
    placementDone: "Placement optimisé !",
    dateUndefined: "date non définie",
    addZone: "Ajouter une zone",
    fullAddress: "Adresse complète",
    venueName: "Nom du lieu",
    venueNotes: "Notes (parking, code)",
    tabPlanDetail: "Tables & Plan",
    rsvpConfirmed: "Confirmés",
    rsvpDeclined: "Refusés",
    rsvpPending: "En attente",
    rsvpRate: "Taux de réponse",
    rsvpLink: "Lien de confirmation invités",
    rsvpStatus: "Statut par invité",
    rsvpTracking: "Suivi par invité",
    rsvpMarkPending: "Marquer tous en attente",
    rsvpConfirmedSingle: "Confirmé",
    rsvpDeclinedSingle: "Décliné",
    yes: "Oui",
    no: "Non",
    paid: "Payé",
    supplier: "Prestataire",
    category: "Catégorie",
    estimated: "Estimé",
    actual: "Réel",
    totalEstimated: "Total estimé",
    totalActual: "Total réel",
    high: "Haute",
    medium: "Moyenne",
    low: "Basse",
    phone: "Téléphone",
    copy: "Copier",
    loginTagline: "La plateforme pro de gestion d'événements",
    loginHero: "Organisez. Placez. Impressionnez.",
    loginSub: "De l'invitation à la salle, gérez chaque détail de votre événement depuis une seule application.",
    loginCta: "Commencer gratuitement avec Google",
    loginFree: "Gratuit · Sans carte bancaire · Synchronisé cloud",
    loginF1: "Plan de salle interactif",
    loginF1d: "Glissez-déposez vos tables sur un canvas intuitif",
    loginF2: "RSVP & invitations",
    loginF2d: "Suivez les confirmations en temps réel",
    loginF3: "Exports premium",
    loginF3d: "PDF, chevalets imprimables, QR codes invités",
    loginF4: "IA proactive",
    loginF4d: "Un assistant qui analyse et guide votre événement",
    loginTrust1: "Mariages",
    loginTrust2: "Galas",
    loginTrust3: "Conférences",
    loginTrust4: "Événements corporate",
    loginFooterTitle: "Prêt à sublimer vos événements ?",
    trustedFor: "Nos clients organisent",
    loginSubtitle: "GESTION DE PLANS DE TABLE",
    
    tabBudget: "💰 Budget",
    tabPlanning: "🗓 Planning",
    tabProgramme: "🎵 Programme",
    tabLogistique: "🗂 Logistique",
    share: "Partager",
    places: "places",
    guestRole: "Rôle",
    settingName: "Nom de l'événement",
    settingDate: "Date",
    settingType: "Type",
    // Notifications
    savedCloud: "☁️ Sauvegardé dans le cloud",
    savedAuto: "☁️ Sauvegardé automatiquement",
    // Voucher
    voucherTitle: "Code promotionnel",
    voucherApplied: "✓ Code appliqué !",
    // Misc
    loading: "Chargement…",
    skipToMain: "Passer au contenu principal",
    note: "📝",
    eventNotes: "LIEU / NOTES INTERNES",
    eventName: "NOM",
    eventDate: "DATE",
    eventType: "TYPE",
    // Stats bar
    statTables: "Tables",
    statGuests: "Invités",
    statSeated: "Placés",
    statWaiting: "En attente",
    statDiets: "Régimes spéciaux",
    // Countdown
    daysAgoLabel: "passé",
    todayLabel: "Aujourd'hui !",
    // Form labels
    fieldName: "NOM *",
    fieldEmail: "EMAIL",
    fieldTable: "TABLE",
    fieldNotes: "NOTES",
    fieldDiet: "RÉGIME",
    fieldAllergies: "ALLERGIES",
    fieldNumber: "NUMÉRO",
    fieldCapacity: "CAPACITÉ",
    fieldShape: "FORME",
    fieldLabel: "ÉTIQUETTE",
    fieldColor: "COULEUR",
    shapeRound: "Ronde",
    shapeRect: "Rectangulaire",
    notSeated: "Non placé",
    addGuestBtn: "Ajouter l'invité",
    createTableBtn: "Créer la table",
    deleteTableBtn: "Supprimer la table",
    settingName: "NOM",
    settingDate: "DATE",
    settingType: "TYPE",
  },

  en: {
    appName: "TableMaître",
    logout: "Sign out",
    lightMode: "Switch to light mode",
    darkMode: "Switch to dark mode",
    codePromo: "Promo code",
    myEvents: "My events",
    welcome: "Welcome",
    searchPlaceholder: "Search an event or a guest...",
    newEvent: "+ New event",
    noEvents: "No events yet",
    createFirst: "Create my first event",
    tables: "tables",
    guests: "guests",
    unseated: "unseated",
    placement: "Seating",
    guestsFound: "guest(s) found",
    duplicate: "Duplicate this event",
    daysAgo: "past",
    today: "Today!",
    inDays: "In",
    days: "d",
    mariage: "Wedding",
    gala: "Gala / Party",
    anniversaire: "Birthday",
    conference: "Conference",
    autre: "Other",
    back: "← Projects",
    autoPlace: "✨ Auto-seat",
    placeCards: "🖨 Place cards",
    floorPlan: "📄 Floor plan PDF",
    qrCode: "QR Code",
    tabPlan: "🗺 Plan",
    tabList: "📋 Liste",
    tabGuests: "👥 Guests",
    tabFood: "🍽 Dietary",
    tabConstraints: "⊘ Constraints",
    tabRoom: "⬡ Room",
    addTable: "+ Table",
    addGuest: "+ Guest",
    dietSummary: "📋 Dietary summary",
    unseatedList: "⚠ UNSEATED",
    seeAvailable: "👁 Show available seats",
    tablesVisible: "✓ Tables highlighted",
    clickToPlace: "👆 Click a table to seat",
    undo: "↩ Undo",
    search: "Search a guest…",
    exportCSV: "⬇ Export CSV",
    importCSV: "⬆ Import CSV",
    tableNumber: "NUMBER",
    tableCapacity: "CAPACITY",
    tableShape: "SHAPE",
    tableLabel: "LABEL",
    tableColor: "COLOR",
    createTable: "Create table",
    deleteTable: "Delete table",
    round: "Round",
    rectangular: "Rectangular",
    guestName: "NAME *",
    guestEmail: "EMAIL",
    guestDiet: "DIET",
    guestAllergies: "ALLERGIES",
    guestTable: "TABLE",
    guestNotes: "NOTES",
    addGuestBtn: "Add guest",
    noTable: "-- Not seated --",
    loginGoogle: "Sign in with Google",
    budgetEstimated: "Estimated budget",
    budgetSpent: "Spent",
    budgetRemaining: "Remaining",
    budgetPerGuest: "Cost / guest",
    budgetActual: "Actual expenses",
    budgetGap: "Gap",
    notPaid: "Unpaid",
    budgetItems: "Expense items",
    budgetLines: "Budget lines",
    fillTemplate: "Fill with template",
    addBudgetLine: "Add item",
    budgetItem: "Item",
    amountEstimated: "Estimated amount (€)",
    amountActual: "Actual amount (€)",
    labelOptional: "Label (optional)",
    tasksTotal: "Total tasks",
    tasksDone: "Done",
    tasksRemaining: "Remaining",
    newTask: "New task",
    templateModel: "Template",
    taskLabel: "Task",
    priority: "Priority",
    details: "Details",
    stepLabel: "Step",
    supplierName: "Name / Company",
    supplierRole: "Role / Service",
    videographer: "Videographer",
    decorator: "Decorator",
    roleMarried: "Married",
    roleWitness: "Witness",
    newConstraint: "New constraint",
    firstGuest: "First guest",
    secondGuest: "Second guest",
    separated: "Separated",
    eventSettings: "Event settings",
    placementDone: "Placement optimized!",
    dateUndefined: "date not set",
    addZone: "Add a zone",
    fullAddress: "Full address",
    venueName: "Venue name",
    venueNotes: "Notes (parking, access)",
    tabPlanDetail: "Tables & Plan",
    rsvpConfirmed: "Confirmed",
    rsvpDeclined: "Declined",
    rsvpPending: "Pending",
    rsvpRate: "Response rate",
    rsvpLink: "Guest confirmation link",
    rsvpStatus: "Guest status",
    rsvpTracking: "Guest tracking",
    rsvpMarkPending: "Mark all pending",
    rsvpConfirmedSingle: "Confirmed",
    rsvpDeclinedSingle: "Declined",
    yes: "Yes",
    no: "No",
    paid: "Paid",
    supplier: "Supplier",
    category: "Category",
    estimated: "Estimated",
    actual: "Actual",
    totalEstimated: "Estimated total",
    totalActual: "Actual total",
    high: "High",
    medium: "Medium",
    low: "Low",
    phone: "Phone",
    copy: "Copy",
    tabBudget: "💰 Budget",
    tabPlanning: "🗓 Planning",
    tabProgramme: "🎵 Programme",
    tabLogistique: "🗂 Logistics",
    share: "Share",
    places: "seats",
    guestRole: "Role",
    settingName: "Event name",
    settingDate: "Date",
    settingType: "Type",
    loginTagline: "The professional event management platform",
    loginHero: "Organize. Place. Impress.",
    loginSub: "From invitations to seating, manage every detail of your event from one powerful application.",
    loginCta: "Get started free with Google",
    loginFree: "Free · No credit card · Cloud synced",
    loginF1: "Interactive floor plan",
    loginF1d: "Drag and drop tables on an intuitive canvas",
    loginF2: "RSVP & invitations",
    loginF2d: "Track confirmations in real time",
    loginF3: "Premium exports",
    loginF3d: "PDF, printable place cards, guest QR codes",
    loginF4: "Proactive AI",
    loginF4d: "An assistant that analyzes and guides your event",
    loginTrust1: "Weddings",
    loginTrust2: "Galas",
    loginTrust3: "Conferences",
    loginTrust4: "Corporate events",
    loginFooterTitle: "Ready to elevate your events?",
    trustedFor: "Our clients organize",
    loginSubtitle: "TABLE PLAN MANAGEMENT",
    savedCloud: "☁️ Saved to cloud",
    savedAuto: "☁️ Auto-saved",
    voucherTitle: "Promotional code",
    voucherApplied: "✓ Code applied!",
    loading: "Loading…",
    skipToMain: "Skip to main content",
    note: "📝",
    eventNotes: "VENUE / INTERNAL NOTES",
    eventName: "NAME",
    eventDate: "DATE",
    eventType: "TYPE",
    // Stats bar
    statTables: "Tables",
    statGuests: "Guests",
    statSeated: "Seated",
    statWaiting: "Waiting",
    statDiets: "Special diets",
    // Countdown
    daysAgoLabel: "past",
    todayLabel: "Today!",
    // Form labels
    fieldName: "NAME *",
    fieldEmail: "EMAIL",
    fieldTable: "TABLE",
    fieldNotes: "NOTES",
    fieldDiet: "DIET",
    fieldAllergies: "ALLERGIES",
    fieldNumber: "NUMBER",
    fieldCapacity: "CAPACITY",
    fieldShape: "SHAPE",
    fieldLabel: "LABEL",
    fieldColor: "COLOR",
    shapeRound: "Round",
    shapeRect: "Rectangular",
    notSeated: "Not seated",
    addGuestBtn: "Add guest",
    createTableBtn: "Create table",
    deleteTableBtn: "Delete table",
    settingName: "NAME",
    settingDate: "DATE",
    settingType: "TYPE",
  },

  es: {
    appName: "TableMaître",
    logout: "Cerrar sesión",
    lightMode: "Cambiar a modo claro",
    darkMode: "Cambiar a modo oscuro",
    codePromo: "Código promocional",
    myEvents: "Mis eventos",
    welcome: "Bienvenido",
    searchPlaceholder: "Buscar un evento o un invitado...",
    newEvent: "+ Nuevo evento",
    noEvents: "No hay eventos por el momento",
    createFirst: "Crear mi primer evento",
    tables: "mesas",
    guests: "invitados",
    unseated: "sin asiento",
    placement: "Asignación",
    guestsFound: "invitado(s) encontrado(s)",
    duplicate: "Duplicar este evento",
    daysAgo: "pasado",
    today: "¡Hoy!",
    inDays: "En",
    days: "d",
    mariage: "Boda",
    gala: "Gala / Fiesta",
    anniversaire: "Cumpleaños",
    conference: "Conferencia",
    autre: "Otro",
    back: "← Proyectos",
    autoPlace: "✨ Auto-sentar",
    placeCards: "🖨 Tarjetas",
    floorPlan: "📄 Plano PDF",
    qrCode: "Código QR",
    tabPlan: "🗺 Plano",
    tabGuests: "👥 Invitados",
    tabFood: "🍽 Alimentación",
    tabConstraints: "⊘ Restricciones",
    tabRoom: "⬡ Sala",
    addTable: "+ Mesa",
    addGuest: "+ Invitado",
    dietSummary: "📋 Resumen dietético",
    unseatedList: "⚠ SIN ASIENTO",
    seeAvailable: "👁 Ver asientos libres",
    tablesVisible: "✓ Mesas destacadas",
    clickToPlace: "👆 Haz clic en una mesa para sentar",
    undo: "↩ Deshacer",
    search: "Buscar un invitado…",
    exportCSV: "⬇ Exportar CSV",
    importCSV: "⬆ Importar CSV",
    tableNumber: "NÚMERO",
    tableCapacity: "CAPACIDAD",
    tableShape: "FORMA",
    tableLabel: "ETIQUETA",
    tableColor: "COLOR",
    createTable: "Crear mesa",
    deleteTable: "Eliminar mesa",
    round: "Redonda",
    rectangular: "Rectangular",
    guestName: "NOMBRE *",
    guestEmail: "EMAIL",
    guestDiet: "DIETA",
    guestAllergies: "ALERGIAS",
    guestTable: "MESA",
    guestNotes: "NOTAS",
    addGuestBtn: "Añadir invitado",
    noTable: "-- Sin asignar --",
    loginGoogle: "Iniciar sesión con Google",
    budgetEstimated: "Presupuesto estimado",
    budgetSpent: "Gastado",
    budgetRemaining: "Restante",
    budgetPerGuest: "Coste / invitado",
    budgetActual: "Gastos reales",
    budgetGap: "Diferencia",
    notPaid: "No pagado",
    budgetItems: "Partidas de gastos",
    budgetLines: "Líneas de presupuesto",
    fillTemplate: "Rellenar con plantilla",
    addBudgetLine: "Añadir partida",
    budgetItem: "Partida",
    amountEstimated: "Importe estimado (€)",
    amountActual: "Importe real (€)",
    labelOptional: "Etiqueta (opcional)",
    tasksTotal: "Tareas totales",
    tasksDone: "Completadas",
    tasksRemaining: "Pendientes",
    newTask: "Nueva tarea",
    templateModel: "Plantilla",
    taskLabel: "Tarea",
    priority: "Prioridad",
    details: "Detalles",
    stepLabel: "Paso",
    supplierName: "Nombre / Empresa",
    supplierRole: "Rol / Servicio",
    videographer: "Videógrafo",
    decorator: "Decorador",
    roleMarried: "Casado/a",
    roleWitness: "Testigo",
    newConstraint: "Nueva restricción",
    firstGuest: "Primer invitado",
    secondGuest: "Segundo invitado",
    separated: "Separados",
    eventSettings: "Configuración del evento",
    placementDone: "¡Colocación optimizada!",
    dateUndefined: "fecha no definida",
    addZone: "Añadir zona",
    fullAddress: "Dirección completa",
    venueName: "Nombre del lugar",
    venueNotes: "Notas (aparcamiento)",
    tabPlanDetail: "Mesas & Plan",
    rsvpConfirmed: "Confirmados",
    rsvpDeclined: "Rechazados",
    rsvpPending: "En espera",
    rsvpRate: "Tasa de respuesta",
    rsvpLink: "Enlace de confirmación",
    rsvpStatus: "Estado por invitado",
    rsvpTracking: "Seguimiento",
    rsvpMarkPending: "Marcar todos en espera",
    rsvpConfirmedSingle: "Confirmado",
    rsvpDeclinedSingle: "Rechazado",
    yes: "Sí",
    no: "No",
    paid: "Pagado",
    supplier: "Proveedor",
    category: "Categoría",
    estimated: "Estimado",
    actual: "Real",
    totalEstimated: "Total estimado",
    totalActual: "Total real",
    high: "Alta",
    medium: "Media",
    low: "Baja",
    phone: "Teléfono",
    copy: "Copiar",
    tabBudget: "💰 Presupuesto",
    tabPlanning: "🗓 Planificación",
    tabProgramme: "🎵 Programa",
    tabLogistique: "🗂 Logística",
    share: "Compartir",
    places: "plazas",
    guestRole: "Rol",
    settingName: "Nombre del evento",
    settingDate: "Fecha",
    settingType: "Tipo",
    loginTagline: "La plataforma profesional de gestión de eventos",
    loginHero: "Organiza. Coloca. Impresiona.",
    loginSub: "Desde las invitaciones hasta la sala, gestiona cada detalle desde una sola aplicación.",
    loginCta: "Comenzar gratis con Google",
    loginFree: "Gratis · Sin tarjeta · Sincronizado en la nube",
    loginF1: "Plano de sala interactivo",
    loginF1d: "Arrastra y suelta mesas en un canvas intuitivo",
    loginF2: "RSVP & invitaciones",
    loginF2d: "Sigue las confirmaciones en tiempo real",
    loginF3: "Exportaciones premium",
    loginF3d: "PDF, tarjetas imprimibles, códigos QR",
    loginF4: "IA proactiva",
    loginF4d: "Un asistente que analiza y guía tu evento",
    loginTrust1: "Bodas",
    loginTrust2: "Galas",
    loginTrust3: "Conferencias",
    loginTrust4: "Eventos corporativos",
    loginFooterTitle: "¿Listo para elevar sus eventos?",
    trustedFor: "Nuestros clientes organizan",
    loginSubtitle: "GESTIÓN DE PLANES DE MESA",
    savedCloud: "☁️ Guardado en la nube",
    savedAuto: "☁️ Guardado automáticamente",
    voucherTitle: "Código promocional",
    voucherApplied: "✓ ¡Código aplicado!",
    loading: "Cargando…",
    skipToMain: "Ir al contenido principal",
    note: "📝",
    eventNotes: "LUGAR / NOTAS INTERNAS",
    eventName: "NOMBRE",
    eventDate: "FECHA",
    eventType: "TIPO",
    // Stats bar
    statTables: "Mesas",
    statGuests: "Invitados",
    statSeated: "Sentados",
    statWaiting: "En espera",
    statDiets: "Dietas especiales",
    daysAgoLabel: "pasado",
    todayLabel: "¡Hoy!",
    fieldName: "NOMBRE *",
    fieldEmail: "EMAIL",
    fieldTable: "MESA",
    fieldNotes: "NOTAS",
    fieldDiet: "DIETA",
    fieldAllergies: "ALERGIAS",
    fieldNumber: "NÚMERO",
    fieldCapacity: "CAPACIDAD",
    fieldShape: "FORMA",
    fieldLabel: "ETIQUETA",
    fieldColor: "COLOR",
    shapeRound: "Redonda",
    shapeRect: "Rectangular",
    notSeated: "Sin asignar",
    addGuestBtn: "Añadir invitado",
    createTableBtn: "Crear mesa",
    deleteTableBtn: "Eliminar mesa",
    settingName: "NOMBRE",
    settingDate: "FECHA",
    settingType: "TIPO",
  },

  de: {
    appName: "TableMaître",
    logout: "Abmelden",
    lightMode: "Zum hellen Modus wechseln",
    darkMode: "Zum dunklen Modus wechseln",
    codePromo: "Aktionscode",
    myEvents: "Meine Veranstaltungen",
    welcome: "Willkommen",
    searchPlaceholder: "Veranstaltung oder Gast suchen...",
    newEvent: "+ Neue Veranstaltung",
    noEvents: "Noch keine Veranstaltungen",
    createFirst: "Meine erste Veranstaltung erstellen",
    tables: "Tische",
    guests: "Gäste",
    unseated: "ohne Platz",
    placement: "Platzierung",
    guestsFound: "Gast/Gäste gefunden",
    duplicate: "Veranstaltung duplizieren",
    daysAgo: "vergangen",
    today: "Heute!",
    inDays: "In",
    days: "T",
    mariage: "Hochzeit",
    gala: "Gala / Party",
    anniversaire: "Geburtstag",
    conference: "Konferenz",
    autre: "Sonstiges",
    back: "← Projekte",
    autoPlace: "✨ Auto-Platzierung",
    placeCards: "🖨 Tischkarten",
    floorPlan: "📄 Saalplan PDF",
    qrCode: "QR-Code",
    tabPlan: "🗺 Plan",
    tabList: "📋 Liste",
    tabGuests: "👥 Gäste",
    tabFood: "🍽 Ernährung",
    tabConstraints: "⊘ Einschränkungen",
    tabRoom: "⬡ Saal",
    addTable: "+ Tisch",
    addGuest: "+ Gast",
    dietSummary: "📋 Ernährungsübersicht",
    unseatedList: "⚠ OHNE PLATZ",
    seeAvailable: "👁 Freie Plätze anzeigen",
    tablesVisible: "✓ Tische hervorgehoben",
    clickToPlace: "👆 Klicke einen Tisch zum Platzieren",
    undo: "↩ Rückgängig",
    search: "Gast suchen…",
    exportCSV: "⬇ CSV exportieren",
    importCSV: "⬆ CSV importieren",
    tableNumber: "NUMMER",
    tableCapacity: "KAPAZITÄT",
    tableShape: "FORM",
    tableLabel: "BEZEICHNUNG",
    tableColor: "FARBE",
    createTable: "Tisch erstellen",
    deleteTable: "Tisch löschen",
    round: "Rund",
    rectangular: "Rechteckig",
    guestName: "NAME *",
    guestEmail: "E-MAIL",
    guestDiet: "ERNÄHRUNG",
    guestAllergies: "ALLERGIEN",
    guestTable: "TISCH",
    guestNotes: "NOTIZEN",
    addGuestBtn: "Gast hinzufügen",
    noTable: "-- Nicht platziert --",
    loginGoogle: "Mit Google anmelden",
    budgetEstimated: "Geschätztes Budget",
    budgetSpent: "Ausgegeben",
    budgetRemaining: "Verbleibend",
    budgetPerGuest: "Kosten / Gast",
    budgetActual: "Tatsächliche Ausgaben",
    budgetGap: "Differenz",
    notPaid: "Nicht bezahlt",
    budgetItems: "Ausgabenposten",
    budgetLines: "Budgetposten",
    fillTemplate: "Mit Vorlage füllen",
    addBudgetLine: "Posten hinzufügen",
    budgetItem: "Posten",
    amountEstimated: "Geschätzter Betrag (€)",
    amountActual: "Tatsächlicher Betrag (€)",
    labelOptional: "Bezeichnung (optional)",
    tasksTotal: "Aufgaben gesamt",
    tasksDone: "Erledigt",
    tasksRemaining: "Verbleibend",
    newTask: "Neue Aufgabe",
    templateModel: "Vorlage",
    taskLabel: "Aufgabe",
    priority: "Priorität",
    details: "Details",
    stepLabel: "Schritt",
    supplierName: "Name / Firma",
    supplierRole: "Rolle / Leistung",
    videographer: "Videograf",
    decorator: "Dekorateur",
    roleMarried: "Verheiratet",
    roleWitness: "Zeuge/Zeugin",
    newConstraint: "Neue Einschränkung",
    firstGuest: "Erster Gast",
    secondGuest: "Zweiter Gast",
    separated: "Getrennt",
    eventSettings: "Veranstaltungseinstellungen",
    placementDone: "Platzierung optimiert!",
    dateUndefined: "Datum nicht festgelegt",
    addZone: "Zone hinzufügen",
    fullAddress: "Vollständige Adresse",
    venueName: "Name des Veranstaltungsortes",
    venueNotes: "Notizen (Parkplatz)",
    tabPlanDetail: "Tische & Plan",
    rsvpConfirmed: "Bestätigt",
    rsvpDeclined: "Abgesagt",
    rsvpPending: "Ausstehend",
    rsvpRate: "Rücklaufquote",
    rsvpLink: "Bestätigungslink",
    rsvpStatus: "Gaststatus",
    rsvpTracking: "Gastverfolgung",
    rsvpMarkPending: "Alle ausstehend markieren",
    rsvpConfirmedSingle: "Bestätigt",
    rsvpDeclinedSingle: "Abgesagt",
    yes: "Ja",
    no: "Nein",
    paid: "Bezahlt",
    supplier: "Lieferant",
    category: "Kategorie",
    estimated: "Geschätzt",
    actual: "Tatsächlich",
    totalEstimated: "Geschätzte Gesamtsumme",
    totalActual: "Tatsächliche Gesamtsumme",
    high: "Hoch",
    medium: "Mittel",
    low: "Niedrig",
    phone: "Telefon",
    copy: "Kopieren",
    tabBudget: "💰 Budget",
    tabPlanning: "🗓 Planung",
    tabProgramme: "🎵 Programm",
    tabLogistique: "🗂 Logistik",
    share: "Teilen",
    places: "Plätze",
    guestRole: "Rolle",
    settingName: "Veranstaltungsname",
    settingDate: "Datum",
    settingType: "Typ",
    loginTagline: "Die professionelle Event-Management-Plattform",
    loginHero: "Organisieren. Platzieren. Beeindrucken.",
    loginSub: "Von der Einladung bis zum Saal — verwalten Sie jedes Detail von einer Anwendung aus.",
    loginCta: "Kostenlos mit Google starten",
    loginFree: "Kostenlos · Keine Kreditkarte · Cloud-synchronisiert",
    loginF1: "Interaktiver Saalplan",
    loginF1d: "Tische per Drag & Drop",
    loginF2: "RSVP & Einladungen",
    loginF2d: "Bestätigungen in Echtzeit verfolgen",
    loginF3: "Premium-Exporte",
    loginF3d: "PDF, druckbare Tischkarten, QR-Codes",
    loginF4: "Proaktive KI",
    loginF4d: "Ein Assistent für Ihr Event",
    loginTrust1: "Hochzeiten",
    loginTrust2: "Galas",
    loginTrust3: "Konferenzen",
    loginTrust4: "Firmenevents",
    loginFooterTitle: "Bereit, Ihre Events zu perfektionieren?",
    trustedFor: "Unsere Kunden organisieren",
    loginSubtitle: "TISCHPLAN-VERWALTUNG",
    savedCloud: "☁️ In der Cloud gespeichert",
    savedAuto: "☁️ Automatisch gespeichert",
    voucherTitle: "Aktionscode",
    voucherApplied: "✓ Code angewendet!",
    loading: "Wird geladen…",
    skipToMain: "Zum Hauptinhalt springen",
    note: "📝",
    eventNotes: "ORT / INTERNE NOTIZEN",
    eventName: "NAME",
    eventDate: "DATUM",
    eventType: "TYP",
    // Stats bar
    statTables: "Tische",
    statGuests: "Gäste",
    statSeated: "Platziert",
    statWaiting: "Wartend",
    statDiets: "Spezialdiäten",
    daysAgoLabel: "vergangen",
    todayLabel: "Heute!",
    fieldName: "NAME *",
    fieldEmail: "E-MAIL",
    fieldTable: "TISCH",
    fieldNotes: "NOTIZEN",
    fieldDiet: "ERNÄHRUNG",
    fieldAllergies: "ALLERGIEN",
    fieldNumber: "NUMMER",
    fieldCapacity: "KAPAZITÄT",
    fieldShape: "FORM",
    fieldLabel: "BEZEICHNUNG",
    fieldColor: "FARBE",
    shapeRound: "Rund",
    shapeRect: "Rechteckig",
    notSeated: "Nicht platziert",
    addGuestBtn: "Gast hinzufügen",
    createTableBtn: "Tisch erstellen",
    deleteTableBtn: "Tisch löschen",
    settingName: "NAME",
    settingDate: "DATUM",
    settingType: "TYP",
  },

  it: {
    appName: "TableMaître",
    logout: "Disconnetti",
    lightMode: "Passa alla modalità chiara",
    darkMode: "Passa alla modalità scura",
    codePromo: "Codice promozionale",
    myEvents: "I miei eventi",
    welcome: "Benvenuto",
    searchPlaceholder: "Cerca un evento o un ospite...",
    newEvent: "+ Nuovo evento",
    noEvents: "Nessun evento al momento",
    createFirst: "Crea il mio primo evento",
    tables: "tavoli",
    guests: "ospiti",
    unseated: "senza posto",
    placement: "Sistemazione",
    guestsFound: "ospite/i trovato/i",
    duplicate: "Duplica questo evento",
    daysAgo: "passato",
    today: "Oggi!",
    inDays: "Tra",
    days: "g",
    mariage: "Matrimonio",
    gala: "Gala / Serata",
    anniversaire: "Compleanno",
    conference: "Conferenza",
    autre: "Altro",
    back: "← Progetti",
    autoPlace: "✨ Disponi automaticamente",
    placeCards: "🖨 Segnaposto",
    floorPlan: "📄 Piano PDF",
    qrCode: "Codice QR",
    tabPlan: "🗺 Piano",
    tabGuests: "👥 Ospiti",
    tabFood: "🍽 Alimentazione",
    tabConstraints: "⊘ Vincoli",
    tabRoom: "⬡ Sala",
    addTable: "+ Tavolo",
    addGuest: "+ Ospite",
    dietSummary: "📋 Riepilogo dietetico",
    unseatedList: "⚠ SENZA POSTO",
    seeAvailable: "👁 Vedi posti liberi",
    tablesVisible: "✓ Tavoli evidenziati",
    clickToPlace: "👆 Clicca un tavolo per sistemare",
    undo: "↩ Annulla",
    search: "Cerca un ospite…",
    exportCSV: "⬇ Esporta CSV",
    importCSV: "⬆ Importa CSV",
    tableNumber: "NUMERO",
    tableCapacity: "CAPACITÀ",
    tableShape: "FORMA",
    tableLabel: "ETICHETTA",
    tableColor: "COLORE",
    createTable: "Crea tavolo",
    deleteTable: "Elimina tavolo",
    round: "Rotondo",
    rectangular: "Rettangolare",
    guestName: "NOME *",
    guestEmail: "EMAIL",
    guestDiet: "DIETA",
    guestAllergies: "ALLERGIE",
    guestTable: "TAVOLO",
    guestNotes: "NOTE",
    addGuestBtn: "Aggiungi ospite",
    noTable: "-- Non assegnato --",
    loginGoogle: "Accedi con Google",
    budgetEstimated: "Budget stimato",
    budgetSpent: "Speso",
    budgetRemaining: "Rimanente",
    budgetPerGuest: "Costo / ospite",
    budgetActual: "Spese reali",
    budgetGap: "Differenza",
    notPaid: "Non pagato",
    budgetItems: "Voci di spesa",
    budgetLines: "Righe di budget",
    fillTemplate: "Compila con modello",
    addBudgetLine: "Aggiungi voce",
    budgetItem: "Voce",
    amountEstimated: "Importo stimato (€)",
    amountActual: "Importo reale (€)",
    labelOptional: "Etichetta (opzionale)",
    tasksTotal: "Attività totali",
    tasksDone: "Completate",
    tasksRemaining: "Rimanenti",
    newTask: "Nuovo compito",
    templateModel: "Modello",
    taskLabel: "Attività",
    priority: "Priorità",
    details: "Dettagli",
    stepLabel: "Passo",
    supplierName: "Nome / Azienda",
    supplierRole: "Ruolo / Servizio",
    videographer: "Videomaker",
    decorator: "Decoratore",
    roleMarried: "Sposato/a",
    roleWitness: "Testimone",
    newConstraint: "Nuovo vincolo",
    firstGuest: "Primo ospite",
    secondGuest: "Secondo ospite",
    separated: "Separati",
    eventSettings: "Impostazioni evento",
    placementDone: "Posizionamento ottimizzato!",
    dateUndefined: "data non definita",
    addZone: "Aggiungi zona",
    fullAddress: "Indirizzo completo",
    venueName: "Nome del luogo",
    venueNotes: "Note (parcheggio)",
    tabPlanDetail: "Tavoli & Piano",
    rsvpConfirmed: "Confermati",
    rsvpDeclined: "Rifiutati",
    rsvpPending: "In attesa",
    rsvpRate: "Tasso di risposta",
    rsvpLink: "Link di conferma",
    rsvpStatus: "Stato ospite",
    rsvpTracking: "Monitoraggio ospiti",
    rsvpMarkPending: "Segna tutti in attesa",
    rsvpConfirmedSingle: "Confermato",
    rsvpDeclinedSingle: "Rifiutato",
    yes: "Sì",
    no: "No",
    paid: "Pagato",
    supplier: "Fornitore",
    category: "Categoria",
    estimated: "Stimato",
    actual: "Reale",
    totalEstimated: "Totale stimato",
    totalActual: "Totale reale",
    high: "Alto",
    medium: "Medio",
    low: "Basso",
    phone: "Telefono",
    copy: "Copia",
    tabBudget: "💰 Budget",
    tabPlanning: "🗓 Pianificazione",
    tabProgramme: "🎵 Programma",
    tabLogistique: "🗂 Logistica",
    share: "Condividi",
    places: "posti",
    guestRole: "Ruolo",
    settingName: "Nome evento",
    settingDate: "Data",
    settingType: "Tipo",
    loginTagline: "La piattaforma professionale di gestione eventi",
    loginHero: "Organizza. Posiziona. Impressiona.",
    loginSub: "Dall'invito alla sala, gestisci ogni dettaglio da un'unica applicazione.",
    loginCta: "Inizia gratis con Google",
    loginFree: "Gratis · Senza carta · Sincronizzato nel cloud",
    loginF1: "Pianta della sala interattiva",
    loginF1d: "Trascina e rilascia i tavoli su una canvas",
    loginF2: "RSVP & inviti",
    loginF2d: "Monitora le conferme in tempo reale",
    loginF3: "Esportazioni premium",
    loginF3d: "PDF, segnaposto stampabili, QR code",
    loginF4: "IA proattiva",
    loginF4d: "Un assistente che guida il tuo evento",
    loginTrust1: "Matrimoni",
    loginTrust2: "Gala",
    loginTrust3: "Conferenze",
    loginTrust4: "Eventi aziendali",
    loginFooterTitle: "Pronti a elevare i vostri eventi?",
    trustedFor: "I nostri clienti organizzano",
    loginSubtitle: "GESTIONE PIANI TAVOLA",
    savedCloud: "☁️ Salvato nel cloud",
    savedAuto: "☁️ Salvato automaticamente",
    voucherTitle: "Codice promozionale",
    voucherApplied: "✓ Codice applicato!",
    loading: "Caricamento…",
    skipToMain: "Vai al contenuto principale",
    note: "📝",
    eventNotes: "LUOGO / NOTE INTERNE",
    eventName: "NOME",
    eventDate: "DATA",
    eventType: "TIPO",
  },    // Stats bar
    statTables: "Tavoli",
    statGuests: "Ospiti",
    statSeated: "Sistemati",
    statWaiting: "In attesa",
    statDiets: "Diete speciali",
    daysAgoLabel: "passato",
    todayLabel: "Oggi!",
    fieldName: "NOME *",
    fieldEmail: "EMAIL",
    fieldTable: "TAVOLO",
    fieldNotes: "NOTE",
    fieldDiet: "DIETA",
    fieldAllergies: "ALLERGIE",
    fieldNumber: "NUMERO",
    fieldCapacity: "CAPACITÀ",
    fieldShape: "FORMA",
    fieldLabel: "ETICHETTA",
    fieldColor: "COLORE",
    shapeRound: "Rotondo",
    shapeRect: "Rettangolare",
    notSeated: "Non assegnato",
    addGuestBtn: "Aggiungi ospite",
    createTableBtn: "Crea tavolo",
    deleteTableBtn: "Elimina tavolo",
    settingName: "NOME",
    settingDate: "DATA",
    settingType: "TIPO",

};

// Détecter la langue du navigateur / pays
function detectLang() {
  const saved = localStorage.getItem('tableMaitreLang');
  if (saved && TRANSLATIONS[saved]) return saved;
  const nav = navigator.language || navigator.languages?.[0] || 'fr';
  const code = nav.slice(0, 2).toLowerCase();
  return TRANSLATIONS[code] ? code : 'en';
}

// Hook i18n
function useI18n() {
  const [lang, setLangState] = useState(detectLang);
  const setLang = (l) => {
    localStorage.setItem('tableMaitreLang', l);
    setLangState(l);
    document.documentElement.lang = l;
  };
  const t = TRANSLATIONS[lang] || TRANSLATIONS.en;
  return { t, lang, setLang };
}

// Drapeaux pour le sélecteur
const LANG_FLAGS = { fr: '🇫🇷', en: '🇬🇧', es: '🇪🇸', de: '🇩🇪', it: '🇮🇹' };
const LANG_NAMES = { fr: 'Français', en: 'English', es: 'Español', de: 'Deutsch', it: 'Italiano' };




const C = {
  dark:   "#120C08",
  mid:    "#2A1A0E",
  card:   "#1E1208",
  gold:   "#C9973A",
  gold2:  "#E8C46A",
  cream:  "#F5EAD4",
  light:  "#EDD9A3",
  muted:  "#8A7355",
  red:    "#C0392B",
  green:  "#27AE60",
  blue:   "#2980B9",
  border: "rgba(201,151,58,0.2)",
};

const THEMES_CONFIG = {
  mariage:      { label: "Mariage",        icon: "💍", color: "#C9973A", bg: "linear-gradient(135deg,#1a0c08,#2a1a0e)" },
  gala:         { label: "Gala / Soirée",  icon: "🥂", color: "#8B7EC8", bg: "linear-gradient(135deg,#0d0a1a,#1a1530)" },
  anniversaire: { label: "Anniversaire",   icon: "🎂", color: "#E8845A", bg: "linear-gradient(135deg,#1a0e08,#2a1810)" },
  conference:   { label: "Conférence",     icon: "🎤", color: "#4A9B7F", bg: "linear-gradient(135deg,#081a12,#0e2a1e)" },
  bapteme:      { label: "Baptême",        icon: "🕊️", color: "#7ABDE8", bg: "linear-gradient(135deg,#081218,#0e1e2a)" },
  loto:         { label: "Loto / Casino",  icon: "🎰", color: "#E84A6A", bg: "linear-gradient(135deg,#1a0810,#2a0e18)" },
  autre:        { label: "Autre",          icon: "🎊", color: "#C9973A", bg: "linear-gradient(135deg,#120c08,#2a1a0e)" },
};

const DIET_OPTIONS = [
  { id: "standard",     label: "Standard",         icon: "🍽️", color: C.muted },
  { id: "vegetarien",   label: "Végétarien",        icon: "🥗", color: "#4CAF50" },
  { id: "vegan",        label: "Vegan",             icon: "🌱", color: "#8BC34A" },
  { id: "sans-gluten",  label: "Sans gluten",       icon: "🌾", color: "#FF9800" },
  { id: "halal",        label: "Halal",             icon: "☪️", color: "#2196F3" },
  { id: "casher",       label: "Casher",            icon: "✡️",  color: "#3F51B5" },
  { id: "sans-lactose", label: "Sans lactose",      icon: "🥛", color: "#9C27B0" },
  { id: "sans-noix",    label: "Allergie noix",     icon: "🥜", color: "#F44336" },
  { id: "sans-fruits-mer", label: "Allergie fruits de mer", icon: "🦞", color: "#E91E63" },
  { id: "diabetique",   label: "Diabétique",        icon: "💊", color: "#607D8B" },
];

// Auth 100% Firebase Google — aucun identifiant stocké dans le code
const INITIAL_USERS = [];

// ═══════════════════════════════════════════════════════════════
// PLANS & VOUCHERS
// ═══════════════════════════════════════════════════════════════

const PLANS = {
  free:   { label: "Gratuit", price: 0,    maxEvents: 1,   maxGuests: 30,  color: "#8A7355", icon: "🆓" },
  pro:    { label: "Pro",     price: 9.90, maxEvents: 999, maxGuests: 999, color: "#C9973A", icon: "⭐" },
  agence: { label: "Agence",  price: 29,   maxEvents: 999, maxGuests: 999, color: "#2A1A0e", icon: "🏢" },
};

const VOUCHERS = {
  "BIENVENUE":   { discount: 100, type: "percent", plan: "pro", description: "1 mois Pro offert 🎁",    maxUses: 999 },
  "MARIAGE2026": { discount: 50,  type: "percent", plan: "pro", description: "-50% sur le plan Pro 💍", maxUses: 100 },
  "PARTENAIRE":  { discount: 30,  type: "percent", plan: "pro", description: "-30% partenaire 🤝",      maxUses: 50  },
  "VIP100":      { discount: 100, type: "percent", plan: "pro", description: "Accès VIP gratuit 👑",    maxUses: 10  },
};


const INITIAL_EVENTS = [
  {
    id: 1, ownerId: "u1",
    name: "Mariage Martin × Dubois", date: "2025-09-14", type: "mariage", plan: "pro",
    roomShape: [
      { x: 60, y: 60 }, { x: 740, y: 60 }, { x: 740, y: 520 },
      { x: 450, y: 520 }, { x: 450, y: 380 }, { x: 60, y: 380 }
    ],
    tables: [
      { id: 1, number: 1, capacity: 8,  x: 160, y: 150, shape: "round",  label: "Famille" },
      { id: 2, number: 2, capacity: 10, x: 350, y: 150, shape: "round",  label: "Amis" },
      { id: 3, number: 3, capacity: 6,  x: 550, y: 150, shape: "round",  label: "Collègues" },
      { id: 4, number: 4, capacity: 8,  x: 160, y: 290, shape: "round",  label: "Famille" },
    ],
    guests: [
      { id: 1, name: "Marie Martin",    email: "marie@test.com",  tableId: 1, diet: "vegetarien",   notes: "", allergies: [] },
      { id: 2, name: "Jean Dupont",     email: "jean@test.com",   tableId: 1, diet: "standard",     notes: "", allergies: [] },
      { id: 3, name: "Sophie Laurent",  email: "",                tableId: 2, diet: "vegan",         notes: "Allergie noix sévère", allergies: ["sans-noix"] },
      { id: 4, name: "Pierre Moreau",   email: "",                tableId: 2, diet: "halal",         notes: "", allergies: [] },
      { id: 5, name: "Julie Petit",     email: "",                tableId: null, diet: "sans-gluten", notes: "", allergies: [] },
    ],
    constraints: [{ id: 1, a: 1, b: 2, type: "together" }],
    menu: { starter: "Velouté de butternut", main: "Filet de bœuf Wellington", dessert: "Pièce montée", vegOption: "Risotto aux champignons" },
  },
  {
    id: 2, ownerId: "u2",
    name: "Loto Municipal Automne", date: "2025-11-02", type: "loto", plan: "free",
    roomShape: [
      { x: 60, y: 60 }, { x: 740, y: 60 }, { x: 740, y: 520 }, { x: 60, y: 520 }
    ],
    tables: [
      { id: 1, number: 1, capacity: 10, x: 200, y: 180, shape: "rect", label: "" },
      { id: 2, number: 2, capacity: 10, x: 420, y: 180, shape: "rect", label: "" },
      { id: 3, number: 3, capacity: 10, x: 620, y: 180, shape: "rect", label: "" },
    ],
    guests: [],
    constraints: [],
    menu: null,
  },
];

// ═══════════════════════════════════════════════════════════════
// UTILS
// ═══════════════════════════════════════════════════════════════

export { TRANSLATIONS, LANG_FLAGS, LANG_NAMES, THEMES_CONFIG, DIET_OPTIONS, INITIAL_USERS, PLANS, VOUCHERS, INITIAL_EVENTS };
